Set true/false for RESTART_SERVERS (empty/not empty before)
gridgain/yardstick pull request #28
Opened 2018-10-17 19:36 UTC by isuntsov-gridgain

I've updated several yardstick scripts and tested 4 scenarios:
1.  RESTART_SERVERS=true ---> All servers will be restarted after each benchmark
2. RESTART_SERVERS=false ---> All servers will be started only 1 time on the start of the run and will be stopped after all benchmarks
3. RESTART_SERVERS=ip:id:delay:pause:period --> 1 server with <id> on host with <ip> will be restarted several times=((duration + warmup)-delay)/(pause+period)
4. RESTART_SERVERS="" - the same behavior with p.1

2018-10-18 06:22 UTC, iartiukhov commented
I think when `RESTART_SERVERS` is `""` (or is not set at all which is the same) we should keep the previous behavior, i.e. threat this case as `"false"`. This will retain backward compatibility and improve understanding.

2018-10-18 08:46 UTC, isuntsov-gridgain commented
@iartiukhov fixed

2018-10-18 09:31 UTC, isuntsov-gridgain commented
@iartiukhov fixed again)

2018-10-18 10:19 UTC, iartiukhov requested changes

2018-10-18 10:19 UTC, iartiukhov commented on bin/benchmark-servers-start.sh
> +if [[ "${RESTART_SERVERS}" != "false" ]] && [[ "${RESTART_SERVERS}" != "true" ]] && [[ "${RESTART_SERVERS}" != "" ]]; then
```suggestion
if [[ "${RESTART_SERVERS}" != "false" ]] && [[ "${RESTART_SERVERS}" != "true" ]]; then
```

2018-10-18 10:19 UTC, iartiukhov commented on bin/benchmark-run-all.sh
> +    if [[ "$RESTART_SERVERS" == "true" || "$RESTART_SERVERS" != "" ]] && [[ "$RESTART_SERVERS" != "false" ]]; then
```suggestion
    if [[ "$RESTART_SERVERS" != "false" ]]; then
```

2018-10-18 10:19 UTC, iartiukhov commented on bin/benchmark-run-all.sh
> +    if [[ "$RESTART_SERVERS" == "true" ]]; then
```suggestion
    if [[ "$RESTART_SERVERS" != "false" ]]; then
```
We should stop servers here if `RESTART_SERVERS` is either `"true"` or `"<IP>:<delay>:<pause>:<period>"`

2018-10-19 10:02 UTC, iartiukhov approved these changes

2018-10-19 10:03 UTC, iartiukhov commented
@isuntsov-gridgain LGTM, thanks. Have you re-tested the fixes?

2018-10-22 11:52 UTC, isuntsov-gridgain commented
@iartiukhov surprisingly, it works)

2018-10-22 13:06 UTC, iartiukhov commented
> @iartiukhov surprisingly, it works)

Great! Let's merge to master.

2018-10-23 12:02 UTC, merged